# Generated by Django 2.0.6 on 2018-06-29 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('so_lam_viec', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('ho_va_ten', models.CharField(max_length=30)),
                ('bo_phan', models.CharField(max_length=30)),
                ('bo_phan_cu_the', models.CharField(max_length=30)),
                ('chuc_vu', models.CharField(max_length=30)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('trang_thai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('skype', models.CharField(max_length=20)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('dien_thoai_2', models.CharField(max_length=20)),
                ('CMND', models.CharField(blank=True, max_length=20)),
                ('highest_education', models.CharField(max_length=40)),
                ('nhi_chu', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('ngay_vao_cong_ty', models.DateField()),
                ('ngay_ra_cong_ty', models.DateField()),
                ('tinh', models.CharField(max_length=20)),
                ('thanh_pho', models.CharField(max_length=20)),
                ('quan_huyen', models.CharField(max_length=20)),
                ('phuong_xa', models.CharField(max_length=20)),
                ('dia_chi_cu_the', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiLam',
            fields=[
                ('STT', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('loai_lam', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gio_quy_dinh_di_lam', models.DateTimeField()),
                ('gio_quy_dinh_tan_lam', models.DateTimeField()),
                ('ghi_chu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhanCongCongViec',
            fields=[
                ('STT', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('ngay_lam', models.DateField()),
                ('trang_thai', models.CharField(max_length=20)),
                ('thoi_gian_di_lam', models.DateTimeField()),
                ('thoi_gian_tan_lam', models.DateTimeField()),
                ('ghi_chu', models.CharField(max_length=50)),
                ('loai_lam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.LoaiLam')),
                ('so_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
