# Generated by Django 2.0.6 on 2018-06-28 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('so_lam_viec', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=30)),
                ('bo_phan', models.CharField(max_length=30)),
                ('dien_thoai', models.CharField(max_length=20)),
                ('thoi_gian_lam', models.DateField()),
                ('thoi_gian_nghie_viec', models.DateField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
