# Generated by Django 2.0.6 on 2018-07-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='bo_phan_id',
            new_name='bo_phan',
        ),
    ]
