# Generated by Django 2.0.6 on 2018-06-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bo_phan_cu_the',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='chuc_vu',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dia_chi_cu_the',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dien_thoai',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dien_thoai_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gioi_tinh',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ngay_ra_cong_ty',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ngay_sinh',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ngay_vao_cong_ty',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nhi_chu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phuong_xa',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='quan_huyen',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skype',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thanh_pho',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tinh',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trang_thai',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='loailam',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
