# Generated by Django 2.0.6 on 2018-06-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180628_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='so_lam_viec',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
