# Generated by Django 2.0.6 on 2018-06-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180629_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='highest_education',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
