# Generated by Django 2.0.6 on 2018-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ngay_ra_cong_ty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ngay_sinh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ngay_vao_cong_ty',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='thoi_gian_di_lam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phancongcongviec',
            name='thoi_gian_tan_lam',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
