# Generated by Django 2.0.6 on 2018-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20180629_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bo_phan',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
