# Generated by Django 2.0.6 on 2018-07-02 00:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giay_san_xuat',
            fields=[
                ('STT', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('MSC', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ngay_san_xuat', models.DateField(blank=True, null=True)),
                ('ngay_nhap_kho', models.DateField(blank=True, null=True)),
                ('so_may_xeo', models.CharField(max_length=10)),
                ('CA', models.CharField(max_length=10)),
                ('giay_loai', models.CharField(max_length=20)),
                ('KL_san_xuat', models.FloatField(blank=True, null=True)),
                ('KLKD', models.CharField(max_length=20)),
                ('chat_luong', models.CharField(max_length=20)),
                ('nguyen_nhan', models.CharField(max_length=50)),
                ('giay_kho', models.IntegerField(blank=True, null=True)),
                ('dinh_luong', models.IntegerField(blank=True, null=True)),
                ('dinh_luong_T_te', models.IntegerField(blank=True, null=True)),
                ('duong_kinh', models.IntegerField(blank=True, null=True)),
                ('do_buc', models.CharField(max_length=20)),
                ('do_am', models.CharField(max_length=20)),
                ('C_tham', models.CharField(max_length=20)),
                ('moi_noi', models.IntegerField(blank=True, null=True)),
                ('ghi_chu', models.CharField(max_length=100)),
                ('so_cong_ty', models.CharField(max_length=20)),
                ('thoi_gian', models.CharField(max_length=20)),
                ('nguoi_ghi_so', models.CharField(max_length=30)),
                ('KCS', models.CharField(max_length=30)),
                ('nguoi_lap_bang', models.CharField(max_length=30)),
                ('tai_xe_kep', models.CharField(max_length=30)),
                ('loai_nhap_kho', models.CharField(max_length=20)),
                ('thoi_gian_bat_dau', models.DateTimeField(blank=True, null=True)),
                ('thoi_gian_ket_thuoc', models.DateTimeField(blank=True, null=True)),
                ('so_giay_lon', models.CharField(max_length=40)),
                ('zhijing', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiayNhapKho',
            fields=[
                ('ngay_nhap_kho', models.DateField(blank=True, null=True)),
                ('MSC', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
    ]
