# Generated by Django 2.0.6 on 2018-06-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giaynhapkho',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='KL_san_xuat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='dinh_luong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='dinh_luong_T_te',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='duong_kinh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='giay_kho',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='moi_noi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='ngay_nhap_kho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='ngay_san_xuat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='thoi_gian_bat_dau',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='thoi_gian_ket_thuoc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='zhijing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giaynhapkho',
            name='ngay_nhap_kho',
            field=models.DateField(blank=True, null=True),
        ),
    ]
