# Generated by Django 2.0.6 on 2018-06-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_auto_20180629_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giay_san_xuat',
            name='MSC',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
